/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompetencyProfileRouteImport } from './routes/competency-profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MyLearningRouteImport } from './routes/my-learning'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as RecommendationsRouteImport } from './routes/recommendations'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SkillGapsRouteImport } from './routes/skill-gaps'
import { Route as SupportRouteImport } from './routes/support'
import { Route as AssessmentsIndexRouteImport } from './routes/assessments/index'
import { Route as AssessmentsReassessmentRouteImport } from './routes/assessments/reassessment'
import { Route as CoursesIndexRouteImport } from './routes/courses/index'
import { Route as CoursesCourseIdRouteImport } from './routes/courses/$courseId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetencyProfileRoute = CompetencyProfileRouteImport.update({
  id: '/competency-profile',
  path: '/competency-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MyLearningRoute = MyLearningRouteImport.update({
  id: '/my-learning',
  path: '/my-learning',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendationsRoute = RecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillGapsRoute = SkillGapsRouteImport.update({
  id: '/skill-gaps',
  path: '/skill-gaps',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentsIndexRoute = AssessmentsIndexRouteImport.update({
  id: '/assessments/',
  path: '/assessments/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentsReassessmentRoute = AssessmentsReassessmentRouteImport.update({
  id: '/assessments/reassessment',
  path: '/assessments/reassessment',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCourseIdRoute = CoursesCourseIdRouteImport.update({
  id: '/courses/$courseId',
  path: '/courses/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/competency-profile': typeof CompetencyProfileRoute
  '/login': typeof LoginRoute
  '/my-learning': typeof MyLearningRoute
  '/progress': typeof ProgressRoute
  '/recommendations': typeof RecommendationsRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/skill-gaps': typeof SkillGapsRoute
  '/support': typeof SupportRoute
  '/assessments/reassessment': typeof AssessmentsReassessmentRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/assessments/': typeof AssessmentsIndexRoute
  '/courses/': typeof CoursesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/competency-profile': typeof CompetencyProfileRoute
  '/login': typeof LoginRoute
  '/my-learning': typeof MyLearningRoute
  '/progress': typeof ProgressRoute
  '/recommendations': typeof RecommendationsRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/skill-gaps': typeof SkillGapsRoute
  '/support': typeof SupportRoute
  '/assessments/reassessment': typeof AssessmentsReassessmentRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/assessments': typeof AssessmentsIndexRoute
  '/courses': typeof CoursesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/competency-profile': typeof CompetencyProfileRoute
  '/login': typeof LoginRoute
  '/my-learning': typeof MyLearningRoute
  '/progress': typeof ProgressRoute
  '/recommendations': typeof RecommendationsRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/skill-gaps': typeof SkillGapsRoute
  '/support': typeof SupportRoute
  '/assessments/reassessment': typeof AssessmentsReassessmentRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/assessments/': typeof AssessmentsIndexRoute
  '/courses/': typeof CoursesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/competency-profile'
    | '/login'
    | '/my-learning'
    | '/progress'
    | '/recommendations'
    | '/settings'
    | '/signup'
    | '/skill-gaps'
    | '/support'
    | '/assessments/reassessment'
    | '/courses/$courseId'
    | '/assessments/'
    | '/courses/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/competency-profile'
    | '/login'
    | '/my-learning'
    | '/progress'
    | '/recommendations'
    | '/settings'
    | '/signup'
    | '/skill-gaps'
    | '/support'
    | '/assessments/reassessment'
    | '/courses/$courseId'
    | '/assessments'
    | '/courses'
  id:
    | '__root__'
    | '/'
    | '/competency-profile'
    | '/login'
    | '/my-learning'
    | '/progress'
    | '/recommendations'
    | '/settings'
    | '/signup'
    | '/skill-gaps'
    | '/support'
    | '/assessments/reassessment'
    | '/courses/$courseId'
    | '/assessments/'
    | '/courses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompetencyProfileRoute: typeof CompetencyProfileRoute
  LoginRoute: typeof LoginRoute
  MyLearningRoute: typeof MyLearningRoute
  ProgressRoute: typeof ProgressRoute
  RecommendationsRoute: typeof RecommendationsRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  SkillGapsRoute: typeof SkillGapsRoute
  SupportRoute: typeof SupportRoute
  AssessmentsReassessmentRoute: typeof AssessmentsReassessmentRoute
  CoursesCourseIdRoute: typeof CoursesCourseIdRoute
  AssessmentsIndexRoute: typeof AssessmentsIndexRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competency-profile': {
      id: '/competency-profile'
      path: '/competency-profile'
      fullPath: '/competency-profile'
      preLoaderRoute: typeof CompetencyProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-learning': {
      id: '/my-learning'
      path: '/my-learning'
      fullPath: '/my-learning'
      preLoaderRoute: typeof MyLearningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommendations': {
      id: '/recommendations'
      path: '/recommendations'
      fullPath: '/recommendations'
      preLoaderRoute: typeof RecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skill-gaps': {
      id: '/skill-gaps'
      path: '/skill-gaps'
      fullPath: '/skill-gaps'
      preLoaderRoute: typeof SkillGapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessments/': {
      id: '/assessments/'
      path: '/assessments'
      fullPath: '/assessments/'
      preLoaderRoute: typeof AssessmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessments/reassessment': {
      id: '/assessments/reassessment'
      path: '/assessments/reassessment'
      fullPath: '/assessments/reassessment'
      preLoaderRoute: typeof AssessmentsReassessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$courseId': {
      id: '/courses/$courseId'
      path: '/courses/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof CoursesCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompetencyProfileRoute: CompetencyProfileRoute,
  LoginRoute: LoginRoute,
  MyLearningRoute: MyLearningRoute,
  ProgressRoute: ProgressRoute,
  RecommendationsRoute: RecommendationsRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  SkillGapsRoute: SkillGapsRoute,
  SupportRoute: SupportRoute,
  AssessmentsReassessmentRoute: AssessmentsReassessmentRoute,
  CoursesCourseIdRoute: CoursesCourseIdRoute,
  AssessmentsIndexRoute: AssessmentsIndexRoute,
  CoursesIndexRoute: CoursesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
